sibelius/ccsseraphini

- src/pages/index.tsx
> https://twitter.com/ftonato/status/1481589521057828865
> feat: adding avatar + textarea to allow users write their messages 🐛

- src/pages/index.tsx
Add a line breaker at sufix to follow how users are used to mention @sibelius
> feat: add a line breaker at user mention

- src/pages/index.tsx
Fixes Issue: #3 
Add a secondary button to allow users to follow sibelius profile in Twitter
> feat: add follow button to sibelius profile

- package.json
- src/components/ForkMeCorner/index.tsx
- src/pages/index.tsx
- yarn.lock
> feat: add github repo link with fork-me corner

- src/pages/index.tsx
- test/pages/index.test.js
This PR adds a newsletter/articles button linking to https://sibelius.substack.com (issue #25)
> feat: add newsletter button

- .babelrc
- package.json
- src/components/ActionButtons.tsx
- src/components/Home.tsx
- test/pages/__tests__/Home.test.tsx
- yarn.lock
Current behaviour:
Proposed behaviour:
----
> I'm also adding the plugin `styled-components` to remove the errors from console related to the `className` property
> refactor: update card in the Home page

- README.md
- apps/cli/README.md
- apps/web/README.md
> feat(docs): add remove on the root of the project

- apps/web/src/components/DonateEth.tsx
Check if metamask is installed (issue #52)
> feat: check if metamask is installed

- apps/cli/bin/cli.js
> fix(cli): bug in conditional

- apps/web/src/components/Timeline.tsx
- apps/web/src/components/TweetInfo.tsx
- apps/web/src/pages/api/latest_tweets.ts
- apps/web/src/types/Tweet.ts
> feat: change tweet info layout

- apps/web/src/components/DonateSol.tsx
The donation crypto using SOL was using a big value in the SVG's `height`, making it impossible to click on button above.
Running the web app and checking the UI.
Nothing.
Hovering the above button.
> fix: DonateSol component svg icon size

- apps/cli/.eslintrc.js
- apps/cli/bin/cli.js
- apps/cli/jest.config.js
- apps/cli/lib/bin/cli.d.ts
- apps/cli/lib/bin/cli.js
- apps/cli/lib/index.d.ts
- apps/cli/lib/index.js
- apps/cli/package-lock.json
- apps/cli/package.json
- apps/cli/src/bin/cli.ts
- apps/cli/src/index.test.ts
- apps/cli/src/index.ts
- apps/cli/tsconfig.json
- apps/cli/yarn.lock
- yarn.lock
As suggested by @sibelius, the CLI is now written in TypeScript.
> feat(cli): cli updated to use typescript

- apps/web/src/components/ActionButtons.tsx
- apps/web/src/components/DonateEth.tsx
- apps/web/src/components/DonateSol.tsx
> fix: home responsive buttons

- apps/web/package.json
- apps/web/src/components/TweetInfo.tsx
- yarn.lock
fix [twitter content](https://github.com/sibelius/ccsseraphini/issues/51#issuecomment-1016753967).
> feat: decode html entities

- apps/web/src/components/pix/DonatePix.tsx
> fix: donate pix button

- apps/web/src/components/TweetInfo.tsx
Prevent TweetInfo component of rerendering every time timeline loads new tweets with infinite scroll.
> feat: memoize tweet info component

- apps/web/src/components/TweetInfo.tsx
- apps/web/src/components/tweetContent.ts
- apps/web/tsconfig.json
> feat: add tweet links

- apps/web/src/components/DonateSol.tsx
Check if Phantom is installed (issue #115)
> feat: Check if Phantom is installed

- apps/web/src/components/ActionButtons.tsx
> fix: change color at mentorship button

- apps/web/src/components/ActionButtons.tsx
> fix: extension and mentorship buttons

- apps/web/src/components/Timeline.tsx
- apps/web/src/pages/api/latest_tweets.ts
- apps/web/src/pages/index.tsx
Some twitter api optimizations:
- Fix duplicated images tweets (issue #131)
- Stop calling the api when there is no more tweets to fetch
Before:
After:
> Twitter api optimizations

- apps/web/package.json
- apps/web/src/components/TweetInfo.tsx
- apps/web/src/components/__tests__/TweetInfo.test.tsx
- yarn.lock
Solves #131 
* What is the feature? Render link preview when there is a non-image url on the tweet.
* How did you implement the solution? I used the `LinkPreview` component provided by https://github.com/Dhaiwat10/react-link-preview and added a variable named `nonImageUrlChunk` that checks whether there is a non-image url on the tweet or not. With that I'm able to render the component conditionally.
> feat: render link preview

- apps/web/src/components/TweetInfo.tsx
- apps/web/src/components/__tests__/TweetInfo.test.tsx
- apps/web/src/components/tweetContent.ts
[x] make hashtag clickable
[x] add test
[x] fix missing prop key
> make hashtags clickable #159

- apps/web/src/components/Timeline.tsx
I have just added a button to refresh the tweets timeline along with some loading animation.
> refresh: adding refresh button and loading

- apps/web/src/components/TweetInfo.tsx
- apps/web/src/components/__tests__/TweetInfo.test.tsx
That pull request is to solve the #160 issue.
> feat(tweetInfo): added link to interactions

- apps/web/src/components/TweetInfo.tsx
> feat: Add replies as tweet stats

- apps/web/src/components/TweetInfo.tsx
> Adding missing LinkBox for replies

- apps/web/src/components/Head.tsx
- apps/web/src/components/score/Score.tsx
- apps/web/src/pages/_app.tsx
- apps/web/src/pages/api/tweets.ts
- apps/web/src/pages/api/userScore.ts
- apps/web/src/pages/index.tsx
- apps/web/src/pages/me.tsx
- apps/web/src/pages/reply.tsx
- apps/web/src/pages/score.tsx
- apps/web/src/pages/search.tsx
- apps/web/src/pages/timeline.tsx
- apps/web/src/types/Score.ts
It's about the #270 yet;
- renamed handlers to normalize;
- created head component to avoid duplicated code;
- added session provider and head component to app;
- changed the result of api/userScore request when the user have not tweets yet to 200.
- removed api/userScore fetch from component
> refactor: removed score fetch from component

- apps/web/package.json
- yarn.lock
Reverts sibelius/ccsseraphini#342
> Revert "build(deps): bump react-is from 17.0.2 to 18.0.0"

- apps/web/src/pages/api/tweets.ts
- apps/web/src/pages/index.tsx
- apps/web/src/pages/me.tsx
- apps/web/src/pages/reply.tsx
- apps/web/src/pages/search.tsx
- apps/web/src/pages/timeline.tsx
Remove tweets from sseraphini_bot on twitter's timeline
> feat(web): remove tweets from sseraphini_bot

- apps/web/src/pages/404.tsx
*  This pull request solve #339  
* Added the page 404 on project
> feat: added page 404

- apps/web/src/components/tweet/TweetPublicMetrics.tsx
- apps/web/src/components/tweet/TweetReplyModal.tsx
Creating a modal to reply a tweet when you click in the count of replies on the Tweet Public Metrics﻿
> feat(TweetPublicMetrics): add modal to reply a tweet

- apps/web/src/components/tweet/TweetPublicMetrics.tsx
Add a button to open the reply tweet modal
https://www.loom.com/share/09beefe7e1c94cb9944a1ae4aa27bc6e
> feat(TweetPublicMetris): Adding button to open the reply tweet modal

- apps/web/src/components/tweet/TweetPublicMetrics.tsx
Change the cursor type to pointer on the LinkBoxes into the `TweetPublicMetrics` component
Issue #363
> refactor(publicMetrics): Add cursor pointer in LinkBox

- apps/web/src/components/__tests__/TweetInfo.test.tsx
- apps/web/src/components/tweet/TweetPublicMetrics.tsx
> refactor(TweetPublicMetrics): Creating component for TweetMetric

- apps/web/src/components/ColorPalette.tsx
- apps/web/src/components/home/Home.tsx
- apps/web/src/components/home/TweetComposer.tsx
- apps/web/src/components/tweet/Timeline.tsx
- apps/web/src/components/tweet/Tweet.tsx
- apps/web/src/components/tweet/TweetPublicMetrics.tsx
- apps/web/src/pages/index.tsx
Changed the default colors to a dark themed palette.
I separated the Palette into its own file so you can edit the colors without needing to change across all the other files.
Todo:
> feat: default dark theme

- apps/web/src/pages/score.tsx
Now when you're on the /score route you can use the input text to search for a twitter username to view they score.
> feat(score): added input field to view scores

- apps/web/src/canvasUtil.tsx
- apps/web/src/components/home/Home.tsx
- apps/web/src/components/home/ScoreButton.tsx
- apps/web/src/components/home/TwitterLogin.tsx
- apps/web/src/getHttpProtocol.tsx
- apps/web/src/pages/api/discord/flood.ts
- apps/web/src/pages/api/discord/oauth.ts
- apps/web/src/pages/index.tsx
- apps/web/src/pages/me.tsx
- apps/web/src/pages/particles.tsx
- apps/web/src/pages/reply.tsx
- apps/web/src/pages/score/[username].tsx
- apps/web/src/pages/search.tsx
- apps/web/src/pages/timeline.tsx
- Added a score button (hidden) that can be displayed when the image share is finished
- Created getHttpProtocol function to stop to repeat code and changed to use http whenever host contains ":3000" or "localhost".
> feat(score): added score button

- apps/web/src/components/home/Home.tsx
- apps/web/src/components/home/ParticleSibAvatar.tsx
- apps/web/src/components/home/useRandom.tsx
- apps/web/src/pages/index.tsx
Adding the same color to the card border and logo of Sibelius
> feat: Same border and color Sibs logo

- apps/web/public/site.webmanifest
Description is good to SEO and may appear on Google search 😳
```
cc @sseraphini connects developers and technology people in an environment where 
everyone can ask their questions and learn in public without having to worry about external 
factors in a win-win relationship.
```
> chore: add application description to webmanifest

- apps/sseramemes/src/config.ts
- apps/sseramemes/src/handleMemeVoting.ts
- apps/sseramemes/src/index.ts
- apps/sseramemes/src/tweetMeme.ts
Automatically retweet memes after some period to improve engagement.
> feat: automatic meme RT after timeout

- .gitignore
- apps/sseramemes/package.json
- apps/sseramemes/scripts/testWatermark.ts
- apps/sseramemes/src/tweetMeme.ts
Added script folder.
Also I found and issue perhaps because we don't have the .env for testing purpose. It breakes have some any ideas how we could solve this @arantespp ?
> (feat): Added scripts folder and testing for watermark

- apps/sseramemes/src/handleMemeVoting.ts
- apps/sseramemes/src/types.ts
- apps/sseramemes/tsconfig.json
Only minor hotfix + type for memeConditions.
> hotfix: removed 'es2020' support from tsconfig + type for memeConditions

- apps/web/src/pages/sibs-day/index.tsx
> fix: official date

- .github/FUNDING.yml
> feat(sponsor): add github sponsor

- apps/web/src/pages/sibs-day/index.tsx
> Fix: Mobile blob

- apps/sseramemes/src/getMessageContent.spec.ts
- apps/sseramemes/src/getMessageContent.ts
- apps/sseramemes/src/handleMemeVoting.ts
- apps/sseramemes/src/tweetMeme.ts
Fix Discord username replacement when tweeting a meme.
> fix: discord user id and username replace

- apps/sseramemes/src/tweetMeme.ts
Add console.err to upload image try/catch
> Add error log

- apps/web/src/pages/sibs-day/index.tsx
> Updating live streaming lunk

- apps/web/src/pages/status.tsx
> feat(status): added static status page

- apps/sseramemes/jest.config.js
- fixed sseramemes tests execution
> fix(jest): changed jest.config to .js to avoid tests breaking

- apps/web/src/components/score/ScoreVisual.tsx
#992 
i fixed that issue using a new link but from the same source (sibs twitter pfp)
> Fix(score): new ccsseraphini icon link

- apps/bot/src/index.ts
> feat: added retry to tweet stream

- apps/sseramemes/src/image-scripts/addLogoToImage.ts
- apps/sseramemes/src/image-scripts/index.ts
- apps/sseramemes/src/image-scripts/resizeImage.ts
Adjusted opacity when image is smol
> feat: adjusted opacity when image is small

- .gitignore
- apps/sseramemes/README.md
- apps/sseramemes/ecosystem.config.js
- apps/sseramemes/package.json
- apps/sseramemes/src/index.ts
- yarn.lock
- [Fix discord.js Intents.](https://stackoverflow.com/a/73324419/8786986)
- Add PM2 scrips and explain how to execute the App on server.
> feat: add pm2 and fix discord

- apps/sseramemes/package.json
- apps/sseramemes/src/index.ts
- yarn.lock
- [Updating Discord.js from v13 to v14.](https://discordjs.guide/additional-info/changes-in-v14.html#before-you-start)
> fix: update discordjs

- apps/sseramemes/README.md
- apps/sseramemes/ecosystem.config.js
As we're running on an EC2 instance, our deployment is a PM2 watch plus a cronjob to pull git changes.
> Sseramemes cicd

- apps/sseramemes/README.md
Update sseramemes README—cronjob command.
> Sseramemes readme

- apps/sseramemes/src/readyMessage.ts
Update sseramemes ready message.
> fix: update sseramemes ready message

- apps/sseramemes/src/handleMemeVoting.ts
- apps/sseramemes/src/instagram.ts
- apps/sseramemes/src/twitterMentions.ts
- Instagram's first algorithm to automate publications.
- Add emoji to begin the bot's message.
> feat: instagram automation

- apps/bot/src/handleThreadCreation.ts
detect forum based on the parent type, instead of the previous workaround
> refactor(bot): improve forum detection

- apps/sseramemes/package.json
- apps/sseramemes/scripts/testAddTextToImage.ts
- apps/sseramemes/src/image-scripts/addTextToImage.ts
- apps/sseramemes/src/image-scripts/index.ts
- apps/sseramemes/src/tweetMeme.ts
title is all bro.
to use is like this:
```bash
;meme text="<text>" position="[<Positions>]" color="[<TextColors>]"
```
```ts
const POSITIONS = {
'top-left': {
x: 0.05,
y: 0.05,
},
'top-center': {
x: 0.3,
y: 0.05,
},
'top-right': {
x: 0.7,
y: 0.05,
},
'middle-left': {
x: 0.05,
y: 0.3,
},
'middle-center': {
x: 0.4,
y: 0.4,
},
'middle-right': {
x: 0.7,
y: 0.3,
},
'bottom-left': {
x: 0.05,
y: 0.7,
},
'bottom-center': {
x: 0.3,
y: 0.7,
},
'bottom-right': {
x: 0.7,
y: 0.7,
},
} as const;
const TEXT_COLORS = {
'small-white': Jimp.FONT_SANS_16_WHITE,
'medium-white': Jimp.FONT_SANS_32_WHITE,
'large-white': Jimp.FONT_SANS_64_WHITE,
'xlarge-white': Jimp.FONT_SANS_128_WHITE,
'small-black': Jimp.FONT_SANS_16_BLACK,
'medium-black': Jimp.FONT_SANS_32_BLACK,
'large-black': Jimp.FONT_SANS_64_BLACK, …
```
> Feat add text to meme to discord bot bot

- apps/sseramemes/README.md
- apps/sseramemes/ecosystem.config.js
> fix: pm2 ignore temp files

- apps/sseramemes/package.json
- yarn.lock
Fix https://github.com/digital-loukoum/esrun/commit/2dd61b0caa9b50a558f17ff9a0d1a79fc709f6f6
> fix: add cuid package

- apps/bot/src/tweetRanking/jobs/getRuleFromConfig.ts
> fix(tweetRanking): :bug: change timezone to use america/sp

- apps/bot/src/date/__tests__/getDayBeforeDate.test.ts
- apps/bot/src/date/__tests__/getFirstDateOfMonth.test.ts
- apps/bot/src/date/__tests__/getLastDayOfMonth.test.ts
- apps/bot/src/date/__tests__/getWeekStartDate.test.ts
- apps/bot/src/date/getDayBeforeDate.ts
- apps/bot/src/date/getFirstDateOfMonth.ts
- apps/bot/src/date/getLastDayOfMonth.ts
- apps/bot/src/date/getWeekStartDate.ts
- apps/bot/src/tweetRanking/__tests__/getStartDateFunctionMap.test.ts
- apps/bot/src/tweetRanking/__tests__/postTweetRanking.test.ts
- apps/bot/src/tweetRanking/getRankingDailyPeriod.ts
- apps/bot/src/tweetRanking/getRankingMonthlyOrBiweeklyPeriod.ts
- apps/bot/src/tweetRanking/getRankingPeriod.ts
- apps/bot/src/tweetRanking/getRankingWeeklyPeriod.ts
- apps/bot/src/tweetRanking/getStartDateFunctionMap.ts
- apps/bot/src/tweetRanking/index.ts
- apps/bot/src/tweetRanking/jobs/getRuleFromConfig.ts
- apps/bot/src/tweetRanking/jobs/rankingJob.ts
- apps/bot/src/tweetRanking/postTweetRanking.ts
> fix(tweetRanking): :ambulance: fixed tweet ranking periods

- apps/web/src/pages/ranking.tsx
minor refactor just to loading before render page
> refactor(ranking): :zap: improve ranking loading

- apps/web/src/components/home/TweetComposer.tsx
Fix in the issue search button: https://github.com/sibelius/ccsseraphini/issues/1014
> fix: button search broken style

- apps/sseramemes/src/addMetadata.ts
- apps/sseramemes/src/tweetMeme.ts
> fix: add alt on if

- apps/web/src/components/home/TweetComposer.tsx
> fix: remove not used component

- apps/sseramemes/src/handleMemeVoting.ts
- apps/sseramemes/src/modules/Publish/publishMemes.ts
- apps/sseramemes/src/tweetMeme.ts
Handle some errors to improve the meme experience
> fix: handle errors

- apps/sseramemes/src/twitterMentions.ts
> fix: add try/catch to twitter mentions

- apps/sseramemes/src/score.ts
One vote is faster, but more votes are safer.
> update score.ts for community safety

- apps/sseramemes/src/handleMemeVoting.ts
- apps/sseramemes/src/index.ts
- apps/sseramemes/src/tweetMeme.ts
Update sseramemes tweet memes to API v2
Fixes #2148
> fix: update tweet meme to v2
